# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyvcloudprovider.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyvcloudprovider.proto',
  package='pyvcloudprovider',
  syntax='proto3',
  serialized_pb=_b('\n\x16pyvcloudprovider.proto\x12\x10pyvcloudprovider\"D\n\x11TenantCredentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0b\n\x03org\x18\x03 \x01(\t\"\x1c\n\x0bLoginResult\x12\r\n\x05token\x18\x01 \x01(\t2a\n\x10PyVcloudProvider\x12M\n\x05Login\x12#.pyvcloudprovider.TenantCredentials\x1a\x1d.pyvcloudprovider.LoginResult\"\x00\x42\x37\n\x1c\x63om.vmware.pyvcloud.providerB\x15PyVcloudProviderProtoP\x01\x62\x06proto3')
)




_TENANTCREDENTIALS = _descriptor.Descriptor(
  name='TenantCredentials',
  full_name='pyvcloudprovider.TenantCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='pyvcloudprovider.TenantCredentials.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='pyvcloudprovider.TenantCredentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='org', full_name='pyvcloudprovider.TenantCredentials.org', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=112,
)


_LOGINRESULT = _descriptor.Descriptor(
  name='LoginResult',
  full_name='pyvcloudprovider.LoginResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='pyvcloudprovider.LoginResult.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['TenantCredentials'] = _TENANTCREDENTIALS
DESCRIPTOR.message_types_by_name['LoginResult'] = _LOGINRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TenantCredentials = _reflection.GeneratedProtocolMessageType('TenantCredentials', (_message.Message,), dict(
  DESCRIPTOR = _TENANTCREDENTIALS,
  __module__ = 'pyvcloudprovider_pb2'
  # @@protoc_insertion_point(class_scope:pyvcloudprovider.TenantCredentials)
  ))
_sym_db.RegisterMessage(TenantCredentials)

LoginResult = _reflection.GeneratedProtocolMessageType('LoginResult', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESULT,
  __module__ = 'pyvcloudprovider_pb2'
  # @@protoc_insertion_point(class_scope:pyvcloudprovider.LoginResult)
  ))
_sym_db.RegisterMessage(LoginResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.vmware.pyvcloud.providerB\025PyVcloudProviderProtoP\001'))

_PYVCLOUDPROVIDER = _descriptor.ServiceDescriptor(
  name='PyVcloudProvider',
  full_name='pyvcloudprovider.PyVcloudProvider',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=144,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='pyvcloudprovider.PyVcloudProvider.Login',
    index=0,
    containing_service=None,
    input_type=_TENANTCREDENTIALS,
    output_type=_LOGINRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYVCLOUDPROVIDER)

DESCRIPTOR.services_by_name['PyVcloudProvider'] = _PYVCLOUDPROVIDER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PyVcloudProviderStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Login = channel.unary_unary(
          '/pyvcloudprovider.PyVcloudProvider/Login',
          request_serializer=TenantCredentials.SerializeToString,
          response_deserializer=LoginResult.FromString,
          )


  class PyVcloudProviderServicer(object):
    """Interface exported by the server.
    """

    def Login(self, request, context):
      """Tenant Loging to VCD  
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PyVcloudProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=TenantCredentials.FromString,
            response_serializer=LoginResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pyvcloudprovider.PyVcloudProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPyVcloudProviderServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Interface exported by the server.
    """
    def Login(self, request, context):
      """Tenant Loging to VCD  
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPyVcloudProviderStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Interface exported by the server.
    """
    def Login(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Tenant Loging to VCD  
      """
      raise NotImplementedError()
    Login.future = None


  def beta_create_PyVcloudProvider_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('pyvcloudprovider.PyVcloudProvider', 'Login'): TenantCredentials.FromString,
    }
    response_serializers = {
      ('pyvcloudprovider.PyVcloudProvider', 'Login'): LoginResult.SerializeToString,
    }
    method_implementations = {
      ('pyvcloudprovider.PyVcloudProvider', 'Login'): face_utilities.unary_unary_inline(servicer.Login),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PyVcloudProvider_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('pyvcloudprovider.PyVcloudProvider', 'Login'): TenantCredentials.SerializeToString,
    }
    response_deserializers = {
      ('pyvcloudprovider.PyVcloudProvider', 'Login'): LoginResult.FromString,
    }
    cardinalities = {
      'Login': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'pyvcloudprovider.PyVcloudProvider', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
