// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pyvcloudprovider.proto

/*
Package pyvcloudprovider is a generated protocol buffer package.

It is generated from these files:
	pyvcloudprovider.proto

It has these top-level messages:
	TenantCredentials
	LoginResult
*/
package pyvcloudprovider

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Tenant VCD crendentials
type TenantCredentials struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Org      string `protobuf:"bytes,3,opt,name=org" json:"org,omitempty"`
}

func (m *TenantCredentials) Reset()                    { *m = TenantCredentials{} }
func (m *TenantCredentials) String() string            { return proto.CompactTextString(m) }
func (*TenantCredentials) ProtoMessage()               {}
func (*TenantCredentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TenantCredentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TenantCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TenantCredentials) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

type LoginResult struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResult) Reset()                    { *m = LoginResult{} }
func (m *LoginResult) String() string            { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()               {}
func (*LoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*TenantCredentials)(nil), "pyvcloudprovider.TenantCredentials")
	proto.RegisterType((*LoginResult)(nil), "pyvcloudprovider.LoginResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PyVcloudProvider service

type PyVcloudProviderClient interface {
	// Tenant Loging to VCD
	Login(ctx context.Context, in *TenantCredentials, opts ...grpc.CallOption) (*LoginResult, error)
}

type pyVcloudProviderClient struct {
	cc *grpc.ClientConn
}

func NewPyVcloudProviderClient(cc *grpc.ClientConn) PyVcloudProviderClient {
	return &pyVcloudProviderClient{cc}
}

func (c *pyVcloudProviderClient) Login(ctx context.Context, in *TenantCredentials, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := grpc.Invoke(ctx, "/pyvcloudprovider.PyVcloudProvider/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PyVcloudProvider service

type PyVcloudProviderServer interface {
	// Tenant Loging to VCD
	Login(context.Context, *TenantCredentials) (*LoginResult, error)
}

func RegisterPyVcloudProviderServer(s *grpc.Server, srv PyVcloudProviderServer) {
	s.RegisterService(&_PyVcloudProvider_serviceDesc, srv)
}

func _PyVcloudProvider_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PyVcloudProviderServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pyvcloudprovider.PyVcloudProvider/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PyVcloudProviderServer).Login(ctx, req.(*TenantCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _PyVcloudProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pyvcloudprovider.PyVcloudProvider",
	HandlerType: (*PyVcloudProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _PyVcloudProvider_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pyvcloudprovider.proto",
}

func init() { proto.RegisterFile("pyvcloudprovider.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xa8, 0x2c, 0x4b,
	0xce, 0xc9, 0x2f, 0x4d, 0x29, 0x28, 0xca, 0x2f, 0xcb, 0x4c, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x57, 0x8a, 0xe5, 0x12, 0x0c, 0x49, 0xcd, 0x4b, 0xcc, 0x2b,
	0x71, 0x2e, 0x4a, 0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0x29, 0x16, 0x92, 0xe2, 0xe2, 0x28,
	0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x10, 0x39, 0x18, 0x5f,
	0x48, 0x80, 0x8b, 0x39, 0xbf, 0x28, 0x5d, 0x82, 0x19, 0x2c, 0x0c, 0x62, 0x2a, 0x29, 0x73, 0x71,
	0xfb, 0xe4, 0xa7, 0x67, 0xe6, 0x05, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08, 0x89, 0x70, 0xb1, 0x96,
	0xe4, 0x67, 0xa7, 0xe6, 0x41, 0x4d, 0x85, 0x70, 0x8c, 0x12, 0xb9, 0x04, 0x02, 0x2a, 0xc3, 0xc0,
	0xee, 0x0a, 0x80, 0xba, 0x4b, 0xc8, 0x97, 0x8b, 0x15, 0xac, 0x51, 0x48, 0x59, 0x0f, 0xc3, 0x2f,
	0x18, 0x0e, 0x96, 0x92, 0xc5, 0x54, 0x84, 0x64, 0xad, 0x12, 0x83, 0x93, 0x39, 0x97, 0x4c, 0x72,
	0x7e, 0xae, 0x5e, 0x59, 0x6e, 0x79, 0x62, 0x51, 0x2a, 0x5c, 0xb1, 0x1e, 0x4c, 0xb5, 0x93, 0x28,
	0xba, 0x03, 0x02, 0x40, 0xe1, 0x15, 0xc0, 0x98, 0xc4, 0x06, 0x0e, 0x38, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x44, 0x5d, 0xe7, 0x21, 0x52, 0x01, 0x00, 0x00,
}
